//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowAppDesktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShowAppDesktop.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string bttnAdd {
            get {
                return ResourceManager.GetString("bttnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string bttnCancel {
            get {
                return ResourceManager.GetString("bttnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string bttnClose {
            get {
                return ResourceManager.GetString("bttnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string bttnDelete {
            get {
                return ResourceManager.GetString("bttnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string bttnEdit {
            get {
                return ResourceManager.GetString("bttnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string bttnExit {
            get {
                return ResourceManager.GetString("bttnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string bttnFind {
            get {
                return ResourceManager.GetString("bttnFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string bttnLoad {
            get {
                return ResourceManager.GetString("bttnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string bttnOpen {
            get {
                return ResourceManager.GetString("bttnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string bttnRemove {
            get {
                return ResourceManager.GetString("bttnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string bttnSave {
            get {
                return ResourceManager.GetString("bttnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string bttnSettings {
            get {
                return ResourceManager.GetString("bttnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative.
        /// </summary>
        internal static string lblAlternative {
            get {
                return ResourceManager.GetString("lblAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending.
        /// </summary>
        internal static string lblEnding {
            get {
                return ResourceManager.GetString("lblEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lblEnglish {
            get {
                return ResourceManager.GetString("lblEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        internal static string lblEpisodes {
            get {
                return ResourceManager.GetString("lblEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string lblGenres {
            get {
                return ResourceManager.GetString("lblGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string lblNotes {
            get {
                return ResourceManager.GetString("lblNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime per Episode.
        /// </summary>
        internal static string lblRuntimeEpisodes {
            get {
                return ResourceManager.GetString("lblRuntimeEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime in Total.
        /// </summary>
        internal static string lblRuntimeTotal {
            get {
                return ResourceManager.GetString("lblRuntimeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string lblScore {
            get {
                return ResourceManager.GetString("lblScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        internal static string lblWatched {
            get {
                return ResourceManager.GetString("lblWatched", resourceCulture);
            }
        }
    }
}
