//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowAppDesktop
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JsonApp.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What item do you want to acces?.
        /// </summary>
        internal static string accesItem {
            get {
                return ResourceManager.GetString("accesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is out of range.
        /// </summary>
        internal static string accesOutofRange {
            get {
                return ResourceManager.GetString("accesOutofRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding complete.
        /// </summary>
        internal static string addComplete {
            get {
                return ResourceManager.GetString("addComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a new item.
        /// </summary>
        internal static string addNewItem {
            get {
                return ResourceManager.GetString("addNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animelon.
        /// </summary>
        internal static string animelon {
            get {
                return ResourceManager.GetString("animelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an Alternative name of the show if it has one.
        /// </summary>
        internal static string assignAlternative {
            get {
                return ResourceManager.GetString("assignAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the description of the show.
        /// </summary>
        internal static string assignDescription {
            get {
                return ResourceManager.GetString("assignDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter if the show has an ending.
        /// </summary>
        internal static string assignEnding {
            get {
                return ResourceManager.GetString("assignEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the English name of the show.
        /// </summary>
        internal static string assignEnglish {
            get {
                return ResourceManager.GetString("assignEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount of episodes of the show.
        /// </summary>
        internal static string assignEpisodes {
            get {
                return ResourceManager.GetString("assignEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the genres of the show.
        /// </summary>
        internal static string assignGenres {
            get {
                return ResourceManager.GetString("assignGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any additional notes about the show.
        /// </summary>
        internal static string assignNotes {
            get {
                return ResourceManager.GetString("assignNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the runtime of a single episode.
        /// </summary>
        internal static string assignRuntime {
            get {
                return ResourceManager.GetString("assignRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the score of the show.
        /// </summary>
        internal static string assignScore {
            get {
                return ResourceManager.GetString("assignScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter if you have already watched it.
        /// </summary>
        internal static string assignWatched {
            get {
                return ResourceManager.GetString("assignWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open a webbrowser to look up more information?.
        /// </summary>
        internal static string browserConfirm {
            get {
                return ResourceManager.GetString("browserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter on what website you want to search.
        /// </summary>
        internal static string browserInput {
            get {
                return ResourceManager.GetString("browserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening a webbrowser.
        /// </summary>
        internal static string browserOpen {
            get {
                return ResourceManager.GetString("browserOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;google&quot; to open up Google
        ///&quot;wiki&quot; to open Wikipedia
        ///&quot;imdb&quot; to open IMDB
        ///&quot;mal&quot; to open MAL
        ///&quot;youtube&quot; to open Youtube
        ///&quot;exit&quot; to back out.
        /// </summary>
        internal static string browserOptions {
            get {
                return ResourceManager.GetString("browserOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string cmdAdd {
            get {
                return ResourceManager.GetString("cmdAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alternative.
        /// </summary>
        internal static string cmdAlternative {
            get {
                return ResourceManager.GetString("cmdAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string cmdDescription {
            get {
                return ResourceManager.GetString("cmdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string cmdEdit {
            get {
                return ResourceManager.GetString("cmdEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ending.
        /// </summary>
        internal static string cmdEnding {
            get {
                return ResourceManager.GetString("cmdEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to english.
        /// </summary>
        internal static string cmdEnglish {
            get {
                return ResourceManager.GetString("cmdEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to episodes.
        /// </summary>
        internal static string cmdEpisodes {
            get {
                return ResourceManager.GetString("cmdEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string cmdExit {
            get {
                return ResourceManager.GetString("cmdExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find.
        /// </summary>
        internal static string cmdFind {
            get {
                return ResourceManager.GetString("cmdFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genres.
        /// </summary>
        internal static string cmdGenres {
            get {
                return ResourceManager.GetString("cmdGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load.
        /// </summary>
        internal static string cmdLoad {
            get {
                return ResourceManager.GetString("cmdLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notes.
        /// </summary>
        internal static string cmdNotes {
            get {
                return ResourceManager.GetString("cmdNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string cmdRemove {
            get {
                return ResourceManager.GetString("cmdRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runtime.
        /// </summary>
        internal static string cmdRuntime {
            get {
                return ResourceManager.GetString("cmdRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        internal static string cmdSave {
            get {
                return ResourceManager.GetString("cmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score.
        /// </summary>
        internal static string cmdScore {
            get {
                return ResourceManager.GetString("cmdScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string cmdSettings {
            get {
                return ResourceManager.GetString("cmdSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to watched.
        /// </summary>
        internal static string cmdWatched {
            get {
                return ResourceManager.GetString("cmdWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crunchyroll.
        /// </summary>
        internal static string crunchyroll {
            get {
                return ResourceManager.GetString("crunchyroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the directory.
        /// </summary>
        internal static string directoryPath {
            get {
                return ResourceManager.GetString("directoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing complete.
        /// </summary>
        internal static string editComplete {
            get {
                return ResourceManager.GetString("editComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What field do you want to edit?.
        /// </summary>
        internal static string editField {
            get {
                return ResourceManager.GetString("editField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;alternative&quot; to edit the alternative name
        ///&quot;english&quot; to edit the english name
        ///&quot;episodes&quot; to edit the amount of episodes
        ///&quot;description&quot; to edit the description
        ///&quot;genres&quot; to edit its genres
        ///&quot;notes&quot; to edit the notes
        ///&quot;score&quot; to edit the score
        ///&quot;runtime&quot; to edit the runtime
        ///&quot;watched&quot; to edit if you have watched it
        ///&quot;ending&quot; to edit if it has an ending
        ///&quot;exit&quot; to stop editing.
        /// </summary>
        internal static string editOptions {
            get {
                return ResourceManager.GetString("editOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding.
        /// </summary>
        internal static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling the search.
        /// </summary>
        internal static string findCancel {
            get {
                return ResourceManager.GetString("findCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to search using: no ?.
        /// </summary>
        internal static string findConfirmNo {
            get {
                return ResourceManager.GetString("findConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to search using: {0} ?.
        /// </summary>
        internal static string findConfirmOther {
            get {
                return ResourceManager.GetString("findConfirmOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to search using: yes ?.
        /// </summary>
        internal static string findConfirmYes {
            get {
                return ResourceManager.GetString("findConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;y&quot; to continue.
        /// </summary>
        internal static string findContinue {
            get {
                return ResourceManager.GetString("findContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it have an ending?.
        /// </summary>
        internal static string findEnding {
            get {
                return ResourceManager.GetString("findEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What field do you want to search in?.
        /// </summary>
        internal static string findField {
            get {
                return ResourceManager.GetString("findField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There hasn&apos;t been any item found in {0} with the term {1} do you want to use a different term?.
        /// </summary>
        internal static string findNoResult {
            get {
                return ResourceManager.GetString("findNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;alternative&quot; to look for the alternative name
        ///&quot;english&quot; to look for the english name
        ///&quot;genres&quot; to look in the genres 
        ///&quot;description&quot; to look in the description 
        ///&quot;watched&quot; to look if you watched it 
        ///&quot;ending&quot; to look if it has an ending 
        ///&quot;exit&quot; to stop searching.
        /// </summary>
        internal static string findOptions {
            get {
                return ResourceManager.GetString("findOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On what do you want to search?.
        /// </summary>
        internal static string findOther {
            get {
                return ResourceManager.GetString("findOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you watched it?.
        /// </summary>
        internal static string findWatched {
            get {
                return ResourceManager.GetString("findWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.
        /// </summary>
        internal static string google {
            get {
                return ResourceManager.GetString("google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imdb.
        /// </summary>
        internal static string imdb {
            get {
                return ResourceManager.GetString("imdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t a valid command please enter a valid command.
        /// </summary>
        internal static string invalidCommand {
            get {
                return ResourceManager.GetString("invalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 English
        ///2 Dutch.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading complete.
        /// </summary>
        internal static string loadComplete {
            get {
                return ResourceManager.GetString("loadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the name of the file?.
        /// </summary>
        internal static string loadFileName {
            get {
                return ResourceManager.GetString("loadFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to give a different directory to load from?.
        /// </summary>
        internal static string loadMode {
            get {
                return ResourceManager.GetString("loadMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;add&quot; to adding a new item
        ///&quot;remove&quot; to remove an excisting item
        ///&quot;find&quot; to find an item
        ///&quot;edit&quot; to edit an excisting item
        ///&quot;save&quot; to save the excisting items
        ///&quot;load&quot; to load items from a file
        ///&quot;settings&quot; to change the settings
        ///&quot;exit&quot; to stop the program.
        /// </summary>
        internal static string mainOptions {
            get {
                return ResourceManager.GetString("mainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mal.
        /// </summary>
        internal static string mal {
            get {
                return ResourceManager.GetString("mal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t a valid number please fill in a number.
        /// </summary>
        internal static string NaN {
            get {
                return ResourceManager.GetString("NaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new language of the application is : .
        /// </summary>
        internal static string newLanguage {
            get {
                return ResourceManager.GetString("newLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string noLong {
            get {
                return ResourceManager.GetString("noLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to serialize a show since it doesn&apos;t have a name.
        /// </summary>
        internal static string noName {
            get {
                return ResourceManager.GetString("noName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string noShort {
            get {
                return ResourceManager.GetString("noShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} isn&apos;t a valid path, resulting to the default path.
        /// </summary>
        internal static string noValidPath {
            get {
                return ResourceManager.GetString("noValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other.
        /// </summary>
        internal static string otherLong {
            get {
                return ResourceManager.GetString("otherLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        internal static string otherShort {
            get {
                return ResourceManager.GetString("otherShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending Program.
        /// </summary>
        internal static string programEnd {
            get {
                return ResourceManager.GetString("programEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Program.
        /// </summary>
        internal static string programStart {
            get {
                return ResourceManager.GetString("programStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling the removal.
        /// </summary>
        internal static string removeCancel {
            get {
                return ResourceManager.GetString("removeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing complete.
        /// </summary>
        internal static string removeComplete {
            get {
                return ResourceManager.GetString("removeComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove:.
        /// </summary>
        internal static string removeConfirm {
            get {
                return ResourceManager.GetString("removeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving complete.
        /// </summary>
        internal static string saveComplete {
            get {
                return ResourceManager.GetString("saveComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should the file be named?.
        /// </summary>
        internal static string saveFileName {
            get {
                return ResourceManager.GetString("saveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to give a directory to store the file on a specific location?.
        /// </summary>
        internal static string saveMode {
            get {
                return ResourceManager.GetString("saveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What language do you want to use?.
        /// </summary>
        internal static string setLanguage {
            get {
                return ResourceManager.GetString("setLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What theme do you want to use?.
        /// </summary>
        internal static string setTheme {
            get {
                return ResourceManager.GetString("setTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What setting you want to change?
        ///&quot;language&quot; or &quot;theme&quot;.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        internal static string settingsLanguage {
            get {
                return ResourceManager.GetString("settingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;language&quot; to change the language
        ///&quot;theme&quot; to editing the theme of the application
        ///&quot;exit&quot; to back out of the settings.
        /// </summary>
        internal static string settingsOptions {
            get {
                return ResourceManager.GetString("settingsOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theme.
        /// </summary>
        internal static string settingsTheme {
            get {
                return ResourceManager.GetString("settingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative name of the show : .
        /// </summary>
        internal static string showAlternative {
            get {
                return ResourceManager.GetString("showAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description : .
        /// </summary>
        internal static string showDescription {
            get {
                return ResourceManager.GetString("showDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has an ending : .
        /// </summary>
        internal static string showEnding {
            get {
                return ResourceManager.GetString("showEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name of the show : .
        /// </summary>
        internal static string showEnglish {
            get {
                return ResourceManager.GetString("showEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Episodes : .
        /// </summary>
        internal static string showEpisodes {
            get {
                return ResourceManager.GetString("showEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres : .
        /// </summary>
        internal static string showGenres {
            get {
                return ResourceManager.GetString("showGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional notes : .
        /// </summary>
        internal static string showNotes {
            get {
                return ResourceManager.GetString("showNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total runtime is {0}:{1} or {2} minutes per episode.
        /// </summary>
        internal static string showRuntime {
            get {
                return ResourceManager.GetString("showRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score : .
        /// </summary>
        internal static string showScore {
            get {
                return ResourceManager.GetString("showScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched : .
        /// </summary>
        internal static string showWatched {
            get {
                return ResourceManager.GetString("showWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Light
        ///2 Dark
        ///3 Matrix.
        /// </summary>
        internal static string themes {
            get {
                return ResourceManager.GetString("themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been changed but not saved, do you want to save it?.
        /// </summary>
        internal static string unsavedChanges {
            get {
                return ResourceManager.GetString("unsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiki.
        /// </summary>
        internal static string wikipedia {
            get {
                return ResourceManager.GetString("wikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string yesLong {
            get {
                return ResourceManager.GetString("yesLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes / No.
        /// </summary>
        internal static string yesNo {
            get {
                return ResourceManager.GetString("yesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes / No / Other.
        /// </summary>
        internal static string yesNoOther {
            get {
                return ResourceManager.GetString("yesNoOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string yesShort {
            get {
                return ResourceManager.GetString("yesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.
        /// </summary>
        internal static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
    }
}
